name: build-and-upload-rekor-v2-dsse

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-sign-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"

      - name: Install jq
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Build binaries
        run: |
          set -euo pipefail
          gcc -O3 -o bin1 src1/hello.c
          gcc -O3 -o bin2 src2/hello2.c
          ls -l bin1 bin2

      - name: Create vigilo statement
        run: |
          set -euo pipefail

          BIN1_SHA384="$(sha384sum bin1 | awk '{print $1}')"
          BIN2_SHA384="$(sha384sum bin2 | awk '{print $1}')"

          echo "bin1 sha384=${BIN1_SHA384}"
          echo "bin2 sha384=${BIN2_SHA384}"

          jq -cn \
            --arg n1 "bin1" \
            --arg h1 "${BIN1_SHA384}" \
            --arg n2 "bin2" \
            --arg h2 "${BIN2_SHA384}" \
            '{
              version: "1.0",
              desc: "Vigilo Artifact Integrity Attestation",
              artifacts: [
                { name: $n1, hash: ("sha384:" + $h1) },
                { name: $n2, hash: ("sha384:" + $h2) }
              ]
            }' > statement.json

          echo "Rendered statement.json:"
          cat statement.json | jq .

      - name: Sign statement and upload DSSE entry to Rekor v2
        id: attest
        uses: JJaaang/attest@main
        with:
          statement-file: statement.json
          payload-type: "application/vnd.in-toto+json"
          // payload-type: "application/vnd.vigilo.attestation+json"

      - name: Upload tlog bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: tlog-bundle
          path:
            statement.json \
            ${{ steps.attest.outputs.envelope-path }} \
            ${{ steps.attest.outputs.tlog-bundle-path }}
